"""relationship

Revision ID: 04104c4612e7
Revises: 5df07ca86d07
Create Date: 2020-10-03 16:57:55.850012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04104c4612e7'
down_revision = '5df07ca86d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('master_id', sa.Integer(), nullable=True))
    op.add_column('room', sa.Column('title', sa.String(), nullable=False))
    op.create_foreign_key(None, 'room', 'user', ['master_id'], ['id'])
    op.add_column('room_member', sa.Column('member_id', sa.Integer(), nullable=True))
    op.add_column('room_member', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'room_member', 'user', ['member_id'], ['id'])
    op.create_foreign_key(None, 'room_member', 'room', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room_member', type_='foreignkey')
    op.drop_constraint(None, 'room_member', type_='foreignkey')
    op.drop_column('room_member', 'room_id')
    op.drop_column('room_member', 'member_id')
    op.drop_constraint(None, 'room', type_='foreignkey')
    op.drop_column('room', 'title')
    op.drop_column('room', 'master_id')
    # ### end Alembic commands ###
