"""attendance

Revision ID: 0a82a10f315e
Revises: 87fce523c78c
Create Date: 2020-11-03 14:09:15.535270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a82a10f315e'
down_revision = '87fce523c78c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_check', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attendance_check', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance_check', type_='foreignkey')
    op.drop_column('attendance_check', 'user_id')
    # ### end Alembic commands ###
