"""add_is_valid

Revision ID: 1f229a3943ce
Revises: 0a82a10f315e
Create Date: 2020-11-04 15:53:41.922752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f229a3943ce'
down_revision = '0a82a10f315e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_check', sa.Column('is_valid', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_check', 'is_valid')
    # ### end Alembic commands ###
