"""add_room_invite_code

Revision ID: 47d6a9f77add
Revises: f15ed813a8c3
Create Date: 2020-10-09 11:56:45.426501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d6a9f77add'
down_revision = 'f15ed813a8c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('invite_code', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'room', ['invite_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room', type_='unique')
    op.drop_column('room', 'invite_code')
    # ### end Alembic commands ###
