"""modified to not unique student_id

Revision ID: 504ce23d5925
Revises: c33afa070174
Create Date: 2020-09-19 18:42:23.701656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504ce23d5925'
down_revision = 'c33afa070174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_student_id_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_student_id_key', 'user', ['student_id'])
    # ### end Alembic commands ###
