"""rank

Revision ID: 5426e39f8e3a
Revises: f41ae37037b8
Create Date: 2020-10-29 17:22:14.942187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5426e39f8e3a'
down_revision = 'f41ae37037b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('rank', sa.String(), server_default='teacher', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rank')
    # ### end Alembic commands ###
