"""add_datetime_to+roommember

Revision ID: 625887e0a995
Revises: 677b675c4e39
Create Date: 2020-10-09 13:54:48.494583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625887e0a995'
down_revision = '677b675c4e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_member', sa.Column('created_on', sa.DateTime(), nullable=False))
    op.add_column('room_member', sa.Column('deleted_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_member', 'deleted_on')
    op.drop_column('room_member', 'created_on')
    # ### end Alembic commands ###
