"""modified_invite_code_to_uuid

Revision ID: 677b675c4e39
Revises: 47d6a9f77add
Create Date: 2020-10-09 12:02:06.118754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677b675c4e39'
down_revision = '47d6a9f77add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
