"""uuid

Revision ID: 87fce523c78c
Revises: 5426e39f8e3a
Create Date: 2020-11-01 02:48:11.326962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87fce523c78c'
down_revision = '5426e39f8e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
