"""modified phone to string type

Revision ID: 8f3041c72c0d
Revises: 504ce23d5925
Create Date: 2020-09-19 18:50:09.665139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f3041c72c0d'
down_revision = '504ce23d5925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
