"""studentid_integer

Revision ID: f15ed813a8c3
Revises: 04104c4612e7
Create Date: 2020-10-06 00:19:18.693206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15ed813a8c3'
down_revision = '04104c4612e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
